# Image Filter Kernels — Interactive Exercises
## Legacy of InFest — Unit VII

Practice convolution and image filtering operations.

In [ ]:
# Setup
import numpy as np

def apply_kernel(image: np.ndarray, kernel: np.ndarray) -> np.ndarray:
    """Apply a 2D convolution kernel to a grayscale image."""
    h, w = image.shape
    kh, kw = kernel.shape
    pad_h, pad_w = kh // 2, kw // 2
    
    padded = np.pad(image, ((pad_h, pad_h), (pad_w, pad_w)), mode='edge')
    result = np.zeros_like(image, dtype=np.float32)
    
    for y in range(h):
        for x in range(w):
            patch = padded[y:y + kh, x:x + kw]
            result[y, x] = np.sum(patch * kernel)
    
    return result

def create_test_image(size: int = 32) -> np.ndarray:
    """Create a test image with a vertical edge."""
    img = np.zeros((size, size), dtype=np.float32)
    img[:, :size//2] = 0.0     # left half: black
    img[:, size//2:] = 1.0     # right half: white
    return img

print('Setup complete!')

### Exercise 1: Identity Kernel

The identity kernel does nothing:
```
[0 0 0]
[0 1 0]
[0 0 0]
```
Apply it to the test image. The output should be identical to the input.

In [ ]:
identity = np.array([[0, 0, 0],
                     [0, 1, 0],
                     [0, 0, 0]], dtype=np.float32)

img = create_test_image()
result = apply_kernel(img, identity)

print(f"Input  (center 5 pixels): {img[16, 14:19]}")
print(f"Output (center 5 pixels): {result[16, 14:19]}")
print(f"Are they equal? {np.allclose(img, result)}")

### Exercise 2: Box Blur Kernel

The box blur kernel averages neighboring pixels:
```
[1/9 1/9 1/9]
[1/9 1/9 1/9]
[1/9 1/9 1/9]
```
Apply it to the test image. The edge should become blurred.

In [ ]:
box_blur = np.ones((3, 3), dtype=np.float32) / 9.0

img = create_test_image()
result = apply_kernel(img, box_blur)

print(f"Input  (center row around edge): {img[16, 14:19]}")
print(f"Output (center row around edge): {result[16, 14:19]}")
print("Notice the edge pixels transition smoothly now.")

### Exercise 3: Sobel Edge Detection

The Sobel X kernel finds vertical edges:
```
[-1 0 1]
[-2 0 2]
[-1 0 1]
```
Apply it to the test image. Where do you see a strong response?

In [ ]:
sobel_x = np.array([[-1, 0, 1],
                    [-2, 0, 2],
                    [-1, 0, 1]], dtype=np.float32)

img = create_test_image()
result = apply_kernel(img, sobel_x)

print("Sobel X response around the vertical edge (column 16):")
print(f"Output (center row): {result[16, 14:19]}")
max_val = np.max(np.abs(result))
print(f"Max response: {max_val:.2f} at edge position")
print("The Sobel kernel responds strongest at edges.")

### Exercise 4: Sharpen Kernel

The sharpen kernel enhances edges:
```
[ 0 -1  0]
[-1  5 -1]
[ 0 -1  0]
```
What happens to the edge when you apply this?

In [ ]:
sharpen = np.array([[0, -1, 0],
                    [-1, 5, -1],
                    [0, -1, 0]], dtype=np.float32)

img = create_test_image()
result = apply_kernel(img, sharpen)

print(f"Input  (around edge): {img[16, 14:19]}")
print(f"Output (around edge): {result[16, 14:19]}")
print("Sharpening increases the contrast at the edge.")

### Exercise 5: Build Your Own Kernel

Design a kernel that detects horizontal edges (lines that go left-to-right).
Hint: a horizontal edge has strong vertical gradient.

In [ ]:
# Create a test image with a horizontal edge
img_h = np.zeros((32, 32), dtype=np.float32)
img_h[:16, :] = 0.0  # top half: black
img_h[16:, :] = 1.0  # bottom half: white

# YOUR CODE: create a Sobel Y kernel (detects horizontal edges)
sobel_y = np.array([
    [0, 0, 0],
    [0, 0, 0],
    [0, 0, 0]
], dtype=np.float32)  # Replace with actual Sobel Y

result = apply_kernel(img_h, sobel_y)
max_val = np.max(np.abs(result))
print(f"Max response: {max_val:.2f} (should be at the horizontal edge, row 16)")
print(f"Output (column 16): {result[14:19, 16]}")